-- SQL for setting up Supabase tables

-- Profiles table (User specific data)
CREATE TABLE profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  full_name TEXT,
  location TEXT,
  phone_number TEXT,
  language_preference TEXT DEFAULT 'en',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Crops Master Data
CREATE TABLE crops_master (
  id SERIAL PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  ideal_soil_ph DECIMAL(3, 1),
  ideal_temp_range NUMERIC[], -- [min, max]
  ideal_rainfall_range NUMERIC[] -- [min, max]
);

-- Crop Recommendations History
CREATE TABLE crop_recommendations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  crop_suggested TEXT NOT NULL,
  confidence DECIMAL(4, 3),
  rationale TEXT,
  actions JSONB,
  soil_parameters JSONB,
  weather_context JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Alerts Table
CREATE TABLE alerts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  severity TEXT CHECK (severity IN ('low', 'medium', 'high', 'critical')),
  read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE crop_recommendations ENABLE ROW LEVEL SECURITY;
ALTER TABLE alerts ENABLE ROW LEVEL SECURITY;

-- Simple Policies (Users can only see their own data)
CREATE POLICY "Users can view their own profile" ON profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can view their own recommendations" ON crop_recommendations FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can view their own alerts" ON alerts FOR SELECT USING (auth.uid() = user_id);
